server:
  port: 9090 
  
spring:
  datasource:
      //url: jdbc:mysql://127.0.0.1:3306/bps_Platform
      url: jdbc:mysql://www.myfalcon.top:3306/bps_Platform
      username: bps
      password: WMC0K/PBXiiytXBrtBnLVLwm2V9nu8f7s7orxloywsMsEnoqxyPF1w5Do/xzIftahyWlayAaQoh7KCt71zy6FQ==
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,config
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKLa1cqCiHFe7YYnFwCNXALokoGYByaRmof049JsYe6Ju+7FMJWn5Ld5hxwEx0rIejZzhMKYPr7oeG+j6Rl2+vUCAwEAAQ==
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true